logging:
  path: ./log/

spring:
  redis:
    host: 127.0.0.1
    password: 123456
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/uexam-mysql?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/exam?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.0.69:3306/exam?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
